services:
  piper:
    build: .
    container_name: piper
    ports:
      - "5000:5000"
    env_file: piper.env
    volumes:
      - piper-models:/app/models
    restart: unless-stopped

volumes:
  piper-models:
